INSERT INTO users ( USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, LASTPASSWORDRESETDATE) VALUES ('admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin',  true, '2016-01-01');
INSERT INTO users ( USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, LASTPASSWORDRESETDATE) VALUES ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', true, '01-01-2016');
INSERT INTO users ( USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, LASTPASSWORDRESETDATE) VALUES ('disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', false, '01-01-2016');

INSERT INTO roles (NAME) VALUES ('ROLE_USER');
INSERT INTO roles (NAME) VALUES ('ROLE_ADMIN');

INSERT INTO user_roles (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO user_roles (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO user_roles (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO user_roles (USER_ID, AUTHORITY_ID) VALUES (3, 1);
